### ISSUE TITLE
Wrong update message when using search filter in plugin table

### ISSUE THREAD

**Issue by kebbet** [WordPress/wp-autoupdates#129] opened 2020-05-14 08:27 UTC
Hi
If I search in the plugin view (which filters all plugins) and press “Enable auto-updates” for a plugin the message above the table is incorrect, and the search is reset. 
The message says “Plugin will no longer be auto-updated.” even though i enabled the auto-update feature. Test done with plugin version 0.8

1. Go to 'wp-admin/plugins.php'
2. Search for any plugin that reduces the view.
3. Click ”Enable auto-update”
4. Wrong message above table, and search is reset.

**Comment by pbiron** [comment] 2020-05-14 14:01
Thank you for the report.  I am able to reproduce this.

There are actually 2 things going on:

1. when the search results are displayed, the `Enable/Disable` links are no longer being handled by Ajax.  That is why the admin notice is then disabled when those links are clicked on after a search, instead of the link text (and some of the link attributes) being updated as happens when no search is done

2. when the `Enable` link are **not** handled by Ajax, you are correct that an incorrect admin notice is shown (auto-updates are correctly enabled, it is just the admin notice that is wrong)

Number 2 is easy to fix, I'll do a PR for in a few minutes.

Number 1 is a harder to deal with, and will take some time figure out a solution.

Again, thanx for reporting this!!

**Comment by pbiron** [comment] 2020-05-14 14:25
A few other points:

1. this problem does **not** happen on the multisite themes screen
    a. the search results on this screen are **not** output via Ajax, so there is no problem with the auto-update `Enable/Disable` links being bound to Ajax actions

2. there appears to be a bug in core with the shinny updates code (which handles the Ajax aspects of searches on the plugins screen)
   a. when an update is available for a plugin and that plugin appears in the search results, the "update" row does **not** appear in the search results

**Before Search**

![before-search](https://user-images.githubusercontent.com/3824560/81945526-74d8a700-95bb-11ea-8d59-8ae3cc38e725.png)

**After Search**

![after-search](https://user-images.githubusercontent.com/3824560/81945597-8ae66780-95bb-11ea-94e2-4423c44e70cc.png)

I'll open a trac ticket about the shinny updates bug.

It is possible that in fixing that bug in core, we can make it easier to fix the problem with the `Enable/Disable` no longer being bound to Ajax actions after a search has been done.

**Comment by pbiron** [comment] 2020-05-14 14:51
Here's the trac ticket: https://core.trac.wordpress.org/ticket/50170

**Comment by azaozz** [comment] 2020-05-16 21:14
> When the search results are displayed, the Enable/Disable links are no longer being handled by Ajax.

Happens because the whole list-table is replaced with the search results. So the `click` handler  is no longer bound to `td.column-auto-updates` (as it is a new node). This is pretty easy to fix, need to bind the click handler to a "lower level" element, usually `document`. Can add to https://github.com/WordPress/wp-autoupdates/pull/130.

**Comment by pbiron** [comment] 2020-05-17 00:00
Fixed in #130

**Closed as completed by pbiron** 2020-05-17 00:00 UTC
Labels: bug
